services:

  client:
    build:
      context: client
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - ./client:/app
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - app-network

  gateway:
    build:
      context: api
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:dev:seed gateway
    env_file:
      - api/.env
    volumes:
      - ./api:/app
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth
      - postgres
    networks:
      - app-network

  user:
    build:
      context: api
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: npm run start:dev user
    env_file:
      - api/.env
    volumes:
      - ./api:/app
    container_name: user
    depends_on:
      - postgres
    networks:
      - app-network

  auth:
    build:
      context: api
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - api/.env
    volumes:
      - ./api:/app
    container_name: auth
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./api/db:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin:rw

networks:
  app-network:
    driver: bridge